[package]
name = "demo_site"
version = "0.1.0"

[dependencies]
iron = "0.4"
mount = "0.2.1"
router = "0.2.0"
handlebars-iron = "0.18.0"
staticfile = "0.3.0"
iron-login = "0.5.0"
toml = "0.1"
bson = "0.1.3"
mongodb = "0.1.0"
params = "0.3.1"