[config]
ip          = "0.0.0.0"
port        = "6767"
public_root = "public"

[config.database]
ip      = "0.0.0.0"
port    = "27017"
db_name = "dev"

[config.database.auth]
username = "admin"
password = "admin"